name: krayn
description: A high-performance cross-platform GUI client for kray KLESS nodes.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.18.0
  http: ^1.2.2
  intl: ^0.20.2
  tray_manager: ^0.5.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/brand/krayn-logo.svg
    - assets/brand/krayn-icon.png
    - assets/brand/krayn-tray.ico

flutter_launcher_icons:
  image_path: assets/brand/krayn-icon.png
  android: true
  min_sdk_android: 21
  adaptive_icon_background: "#08343a"
  adaptive_icon_foreground: assets/brand/krayn-icon.png
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: assets/brand/krayn-icon.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/brand/krayn-icon.png
